#!usr/bin/env python
# -*- coding:utf-8 -*-

name = raw_input("Username:")
Password = raw_input('Password:')
#当账户密码输入错误时，先循环执行name，再执行Password

while  Password !='123456'or name != "tz950313" : 
	print(" Please input the correct username password ")
	name = raw_input("Username:")	
	Password = raw_input('Password:') #当账户密码输入正确时，输出账户、密码，进行下一步操作

import time
i = 5
i=i-1

while i!='1' and i>1:
	time.sleep(1)
	i=i-1
	print ('>>>'),i
	
time.sleep(1)

print("success login")

#raw_input("\n\npress the enter key to exit.")
