#!usr/bin/env python
#-*- coding:utf-8 -*-
s = raw_input("number:")#生成随机密码的个数
l = raw_input("long:")#随机密码长度
from random import choice
import string
import getpass
def GenPassword(length=8,chars=string.ascii_letters+string.digits):
    return ''.join([choice(chars) for i in range(length)])
if __name__=="__main__":
	for i in range(int(s)): 
		print i,":",(GenPassword(int(l)))
